server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications?connectionTimeZone=Asia/Kolkata
    username: vinay
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # ⚠️ dev only
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  mail:
    port: 587
    host: email-smtp.ap-south-1.amazonaws.com
    username: ${SES_SMTP_USER}
    password: ${SES_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.vinay.ratelimiter.api.dto.NotificationRequest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: notification-service

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  from-number: ${TWILIO_FROM_NUMBER}
  message-service-sid: ${TWILIO_MESSAGE_SERVICE_SID}

aws:
  region: ${AWS_REGION}

logging:
  level:
    com.vinay.ratelimiter: DEBUG
